#!/usr/bin/env bash
# Install user systemd timer for website stock allowlist Magento sync (#182).
#
# Usage:
#   ./scripts/ops/install_website_stock_timer.sh
#   systemctl --user status depotru-website-stock-allowlist.timer
#   journalctl --user -u depotru-website-stock-allowlist.service -n 50
#
set -euo pipefail

REPO="$(cd "$(dirname "$0")/../.." && pwd)"
UNIT_DIR="${HOME}/.config/systemd/user"
ENV_DIR="${HOME}/.config/depotru"
ENV_FILE="${ENV_DIR}/website-stock.env"
DEPO_ENV="${HOME}/Projects/depositotrujillo.co/config/env.php"

mkdir -p "${UNIT_DIR}" "${ENV_DIR}"

# Build env file if missing (DB from depotru .env; Magento SSH from sibling env.php)
if [[ ! -f "${ENV_FILE}" ]]; then
  echo "Creating ${ENV_FILE}"
  {
    echo "# Generated by install_website_stock_timer.sh — do not commit"
    echo "# DB: reuse depotru .env via EnvironmentFile if you prefer; here we set Magento SSH"
    if [[ -f "${REPO}/.env" ]]; then
      # shellcheck disable=SC1090
      set -a
      # shellcheck source=/dev/null
      source "${REPO}/.env" 2>/dev/null || true
      set +a
      # Export common DB vars if present
      for v in NCX_FILE_PATH DB_HOST DB_SERVER DB_PORT DB_USER DB_PASSWORD DB_NAME DB_NAME_J3SYSTEM; do
        if [[ -n "${!v:-}" ]]; then
          printf '%s=%s\n' "$v" "${!v}"
        fi
      done
    fi
    echo "MAGENTO_SSH_HOST=174.142.205.80"
    echo "MAGENTO_SSH_USER=deptrujillob2c"
    echo "MAGENTO_ROOT=/home/deptrujillob2c/public_html"
    echo "MAGENTO_ENV_PHP=${DEPO_ENV}"
  } > "${ENV_FILE}"
  chmod 600 "${ENV_FILE}"
  echo "Wrote ${ENV_FILE} (mode 600). Edit if needed."
else
  echo "Keeping existing ${ENV_FILE}"
fi

install -m 644 "${REPO}/deploy/systemd/depotru-website-stock-allowlist.service" \
  "${UNIT_DIR}/depotru-website-stock-allowlist.service"
install -m 644 "${REPO}/deploy/systemd/depotru-website-stock-allowlist.timer" \
  "${UNIT_DIR}/depotru-website-stock-allowlist.timer"

# Fix WorkingDirectory / ExecStart if repo not under ~/Projects/depotru_database
if [[ "${REPO}" != "${HOME}/Projects/depotru_database" ]]; then
  sed -i "s|%h/Projects/depotru_database|${REPO}|g" \
    "${UNIT_DIR}/depotru-website-stock-allowlist.service"
fi

systemctl --user daemon-reload
systemctl --user enable --now depotru-website-stock-allowlist.timer

echo ""
echo "Installed depotru-website-stock-allowlist.timer"
systemctl --user list-timers depotru-website-stock-allowlist.timer --no-pager || true
echo ""
echo "Manual run:"
echo "  systemctl --user start depotru-website-stock-allowlist.service"
echo "  journalctl --user -u depotru-website-stock-allowlist.service -n 40 --no-pager"
echo "  tail -5 ~/business_reports/website_stock_allowlist_sync.log"
echo ""
echo "Dry-run without Magento write:"
echo "  cd ${REPO} && PYTHONPATH=src .venv/bin/python scripts/ops/run_website_stock_allowlist_sync.py --dry-run"
