#!/usr/bin/env bash
# Install (opt-in) user systemd units for the Monday cash pack.
#
# Default: copy units only. Does NOT enable or start the timer.
# Enable explicitly:
#   ./scripts/ops/install_monday_cash_pack_timer.sh --enable
#
set -euo pipefail

ENABLE=0
if [[ "${1:-}" == "--enable" ]]; then
  ENABLE=1
fi

REPO="$(cd "$(dirname "$0")/../.." && pwd)"
UNIT_DIR="${HOME}/.config/systemd/user"
ENV_DIR="${HOME}/.config/depotru"
ENV_FILE="${ENV_DIR}/monday-cash-pack.env"

mkdir -p "${UNIT_DIR}" "${ENV_DIR}"

if [[ ! -f "${ENV_FILE}" ]]; then
  echo "Creating ${ENV_FILE}"
  {
    echo "# Generated by install_monday_cash_pack_timer.sh — do not commit"
    echo "# Reuse depotru .env for DB. SMTP is optional; the job writes drafts only."
    if [[ -f "${REPO}/.env" ]]; then
      # shellcheck disable=SC1090
      set -a
      # shellcheck source=/dev/null
      source "${REPO}/.env" 2>/dev/null || true
      set +a
      for v in NCX_FILE_PATH DB_HOST DB_SERVER DB_PORT DB_USER DB_PASSWORD DB_NAME \
               OUTPUT_DIR SMTP_HOST SMTP_PORT SMTP_USER MAIL_FROM MAIL_TO; do
        if [[ -n "${!v:-}" ]]; then
          printf '%s=%s\n' "$v" "${!v}"
        fi
      done
    fi
    echo "# SMTP_HOST="
    echo "# MAIL_TO="
  } > "${ENV_FILE}"
  chmod 600 "${ENV_FILE}"
  echo "Wrote ${ENV_FILE} (mode 600). Edit if needed."
else
  echo "Keeping existing ${ENV_FILE}"
fi

install -m 644 "${REPO}/deploy/systemd/depotru-monday-cash-pack.service" \
  "${UNIT_DIR}/depotru-monday-cash-pack.service"
install -m 644 "${REPO}/deploy/systemd/depotru-monday-cash-pack.timer" \
  "${UNIT_DIR}/depotru-monday-cash-pack.timer"

if [[ "${REPO}" != "${HOME}/Projects/depotru_database" ]]; then
  sed -i "s|%h/Projects/depotru_database|${REPO}|g" \
    "${UNIT_DIR}/depotru-monday-cash-pack.service"
fi

systemctl --user daemon-reload

echo ""
echo "Installed unit files (disabled by default)."
if [[ "${ENABLE}" -eq 1 ]]; then
  systemctl --user enable --now depotru-monday-cash-pack.timer
  echo "Enabled depotru-monday-cash-pack.timer"
  systemctl --user list-timers depotru-monday-cash-pack.timer --no-pager || true
else
  echo "Timer is NOT enabled. To opt in:"
  echo "  systemctl --user enable --now depotru-monday-cash-pack.timer"
fi

echo ""
echo "Manual draft run:"
echo "  cd ${REPO} && PYTHONPATH=src .venv/bin/python scripts/reports/run_monday_cash_pack.py --synthetic"
echo "  systemctl --user start depotru-monday-cash-pack.service"
echo "The service never passes --send."
